### PR TITLE
Fix superagent.agent is not a function

### PR DESCRIPTION
**Pull request by medson10**

### CODE REVIEW

**Comment by kierenj** [comment]
Thanks very much for the PR - glad you found the project useful :)

I'm keen to learn how you encountered this error, and whether this fixed the situation you had.

We use `.agent()` here because it creates an agent which persists cookies (as per http://visionmedia.github.io/superagent/#agents-for-global-state).

**Comment by medson10** [comment]
When I tried to use this module I got the error, "superagent.agent is not a function" then I seen in the code of the superagent and doesn't have the agent method, to you create a agent must use superagent()

**Comment by kierenj** [comment]
But as per my link to their documentation, and myself and other users’ experience, it does exist and work... I can see that for some non-node use case it doesnt have the function - can i ask how youre using the library for your project please? And does all the functionality work without the agent call? I thought guerillamail used cookies..!

**Comment by medson10** [comment]
I'm using for test a function of send email, I create a email with the guerrilla, call a function to send the email in the application and then I use the guerrilla again to check if the email have arrived. 
I didn't change anything else, I installed the module and then I received this error when I tried to use

**Comment by kierenj** [comment]
I'm sorry to make work for you, but would you be able to share a small project that reproduces the issue?  I've tried again and it seems to work fine here - and other users of the library have been able to get it working OK.  I'd just like to be able to narrow down and identify the issue and what's causing it, if that's ok?

**Comment by medson10** [comment]
hmm I'm using the guerrillamail to test a function of send email, and by what I saw the problem is an update in the superagent module, take a look in the repository, they are using in a different way. https://github.com/visionmedia/superagent

**Comment by medson10** [comment]
the code what I'm using in my tests 

`const mailbox = new TempMailbox()

  const getEmail = () => {
    return new Cypress.Promise((resolve, reject) => {
      mailbox.getEmailAddress().then(addr => {
        resolve(addr)
      })
    })
  }

  const getEmails = () => {
    return new Cypress.Promise((resolve, reject) => {
      mailbox
        .waitForEmail(m => {
          return m.mail_subject.indexOf('Test') !== -1
        })
        .then(mail => {
          const message = mail.mail_body
          mailbox.deleteMail(mail.mail_id)
          const link = message.match(/<p>(.*?)<\/p>/g).map(val => {
            return val.replace(/<\/?p>/g, '')
          })
          resolve(link, mail.mail_id)
          mailbox.deleteMail(mail.mail_id)
        })
    })
  }
`

**Pull request closed without merging**
